name: CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: check out repo
        uses: actions/checkout@v7
      - name: set up python
        uses: actions/setup-python@v6
        with:
          cache: 'pip'
      - name: install deps
        run: |
          python -m pip install --upgrade pip
          pip install ruff pyright pytest
          pip install -e .
      - name: format
        run: ruff format --check .
      - name: lint
        run: ruff check .
      - name: type check
        run: pyright .
      - name: test
        run: pytest tests/ -v
